inherit_from: configs/ScanNet/scannet.yaml
tracking:
  w_sdf_fs: 10
  w_sdf_center: 500
  w_sdf_tail: 50
mapping:
  bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
  marching_cubes_bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
  w_sdf_fs: 5
  w_sdf_center: 500
  w_sdf_tail: 10
data:
  input_folder: /media/funcdecl/Data/all_datasets/scannet/scans/scene0207_00
  output: output/scannet/scans/scene0207_00