inherit_from: configs/ScanNet/scannet.yaml
tracking:
  w_sdf_fs: 10
  w_sdf_center: 200
  w_sdf_tail: 50
mapping:
  bound: [[-1.1,9.8],[-1.0,10.0],[-1.0,4.3]]
  marching_cubes_bound: [[-1.1,9.8],[-1.0,10.0],[-1.0,4.3]]
  w_sdf_fs: 5
  w_sdf_center: 200
  w_sdf_tail: 10
data:
  input_folder: /media/funcdecl/Data/all_datasets/scannet/scans/scene0106_00
  output: output/scannet/scans/scene0106_00