inherit_from: configs/ScanNet/scannet.yaml
tracking:
  w_sdf_fs: 10
  w_sdf_center: 200
  w_sdf_tail: 50

mapping:
  bound: [[-0.2,9.8],[-1.0,8.5],[-1.0,3.4]]
  marching_cubes_bound: [[-0.2,9.8],[-1.0,8.5],[-1.0,3.4]]
  w_sdf_fs: 5
  w_sdf_center: 200
  w_sdf_tail: 10

data:
  input_folder: /media/funcdecl/Data/all_datasets/scannet/scans/scene0169_00
  output: output/scannet/scans/scene0169_00