dataset: 'tumrgbd'
meshing:
  resolution: 0.01 #cm # Increase this number to speed up meshing algorithm
  eval_rec: False
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.005
  lr_R: 0.0025
  pixels: 5000
  iters: 200
mapping:
  every_frame: 1
  keyframe_every: 1
  pixels: 10000
  iters: 150
  weight_c_requires_grad: True
  keyframe_selection_method: 'global'
cam:  #NOTE: intrinsic is different per scene in TUM
  H: 480
  W: 640
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  png_depth_scale: 5000.0
  crop_edge: 0
rendering:
  n_stratified: 48
  n_importance: 8
  learnable_beta: False
training:
  lr_small: 0.001
  lr_large: 0.005