scale: 1
verbose: False
device: "cuda:0"
keyframe_device: "cuda:0" ## Change this to "cpu" to reduce GPU memory usage

meshing:
  level_set: 0
  resolution: 0.01 #cm # Increase this number to speed up meshing algorithm
  eval_rec: False
  mesh_bound_scale: 1.02
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  vis_freq: 40
  vis_inside_freq: 40
  const_speed_assumption: True
  no_vis_on_first_frame: True
  gt_camera: False
  lr_T: 0.001
  lr_R: 0.001
  pixels: 2000
  iters: 8
  w_sdf_fs: 10
  w_sdf_center: 5000
  w_sdf_tail: 50
  w_depth: 1
  w_color: 5
mapping:
  every_frame: 4
  joint_opt: True
  joint_opt_cam_lr: 0.001
  no_vis_on_first_frame: True
  no_mesh_on_first_frame: True
  no_log_on_first_frame: True
  vis_freq: 40
  vis_inside_freq: 40 #each iteration
  mesh_freq: 4000
  ckpt_freq: 500
  keyframe_every: 4
  mapping_window_size: 20 #最多64个optimizer frames，设置62
  keyframe_selection_method: 'overlap'
  lr_first_factor: 1
  lr_factor: 1
  pixels: 4000
  iters_first: 1000
  iters: 15
  w_sdf_fs: 5
  w_sdf_center: 2000
  w_sdf_tail: 10
  w_depth: 0.1
  w_color: 5
  scene_reso_c: 768
  scene_reso_g: 384
  weight_c_requires_grad: False

cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0

rendering:
  n_stratified: 32
  n_importance: 8
  perturb: True
  learnable_beta: True
  max_samples: 128
  step_ratio: 0.5

  fea2denseAct: 'softplus'
  density_shift: -10
  distance_scale: 25.0

  view_pe: 6
  fea_pe: 0

  lindisp: 0

  alphaMask_thres: 0.02
  rayMarch_weight_thres: 0.001

  num_layers: 2
  hidden_dim: 128

model:
  c_dim: 32
  truncation: 0.06
  coeff_reso: 32
  coeff_g_init: 0.05
  coeff_c_init: 1.0
  coeff_type: 'grid'
  basis_type: 'grid'
  basis_mapping: 'sawtooth'
  basis_dims: [4,4,4,2,2,2]
  basis_resos: [ 32,51,70,89,108,128 ]
  freq_bands: [ 2., 3.2, 4.4, 5.6, 6.8, 8. ]
  total_params: 5313942

  in_dim: 3
  out_dim: 1
  num_layers: 1
  hidden_dim: 64
  feat_c_dim: 18

training:
  viewdirs: False

  L1_weight_rest: 0.1
  lr_small: 0.001
  lr_large: 0.02
  lr_decay_target_ratio: 0.1
  volume_resoInit: 128 # 128**3：
  volume_resoFinal: 300 # 300**3
  perturb: 1
  trunc: 0.1

  sdf_lambda: 5
data:
  sc_factor: 1
